CREATE SEQUENCE ODPT.odpt_big_s START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ODPT.odpt_number_s START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ODPT.odpt_object_s START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ODPT.odpt_logs_s START WITH 1 INCREMENT BY 1;
