//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Odapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;oracle.manageddataaccess.client&quot; type=&quot;OracleInternal.Common.ODPMSectionHandler, Oracle.ManagedDataAccess, Version=4.122.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342&quot;/&gt;
        ///    &lt;/configSections&gt;
        ///&lt;startup&gt;&lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.2&quot;/&gt;&lt;/startup&gt;
        ///&lt;system.data&gt;
        ///&lt;DbProviderFactories&gt;
        ///&lt;remove invariant=&quot;Oracle.ManagedDataAccess.Client&quot;/&gt;
        ///&lt;add name=&quot;ODP.NET, Managed Dri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        /////    Odapter - a C# code generator for Oracle packages
        /////    Copyright(C) 2021 Clay Lipscomb
        /////
        /////    This program is free software: you can redistribute it and/or modify
        /////    it under the terms of the GNU General Public License as published by
        /////    the Free Software Foundation, either version 3 of the License, or
        /////    (at your option) any later version.
        /////
        /////    This program is distributed in the hope that it will [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaseConversion {
            get {
                return ResourceManager.GetString("CaseConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        /////    Odapter - a C# code generator for Oracle packages
        /////    Copyright(C) 2021 Clay Lipscomb
        /////
        /////    This program is free software: you can redistribute it and/or modify
        /////    it under the terms of the GNU General Public License as published by
        /////    the Free Software Foundation, either version 3 of the License, or
        /////    (at your option) any later version.
        /////
        /////    This program is distributed in the hope that it will [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrclPower {
            get {
                return ResourceManager.GetString("OrclPower", resourceCulture);
            }
        }
    }
}
