//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Odapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;oracle.manageddataaccess.client&quot;
        ///      type=&quot;OracleInternal.Common.ODPMSectionHandler, Oracle.ManagedDataAccess, Version=4.122.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342&quot;/&gt;
        ///    &lt;/configSections&gt;
        ///&lt;startup&gt;&lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.0&quot;/&gt;&lt;/startup&gt;
        ///&lt;system.data&gt;
        ///&lt;DbProviderFactories&gt;
        ///&lt;remove invariant=&quot;Oracle.ManagedDataAccess.Client&quot;/&gt;
        ///&lt;add name=&quot;ODP.NET, Manage [rest of string was truncated]&quot;;.
        /// </summary>
        public static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Globalization;
        ///using System.Text.RegularExpressions;
        ///
        ///namespace CaseConversion {
        ///    /// &lt;summary&gt;
        ///    /// Converts between various &quot;cases&quot; like camelCase, PascalCase, underscore_delimited
        ///    /// &lt;/summary&gt;
        ///    public class CaseConverter {
        ///        #region Constant and Static members
        ///        private const char UNDERSCORE = &apos;_&apos;;
        ///        private const string UNDERSCORECHAR_WORD = &quot;underscorechar&quot;;
        ///        private static TextInfo _textInfo = new CultureInfo(&quot;en-US&quot;, false [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaseConversion {
            get {
                return ResourceManager.GetString("CaseConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Reflection;
        ///using System.Data;
        ///#if CSHARP30
        ///using Oracle.DataAccess.Client;
        ///using Oracle.DataAccess.Types;
        ///#else
        ///using Oracle.ManagedDataAccess.Client;
        ///using Oracle.ManagedDataAccess.Types;
        ///#endif
        ///using System.Linq;
        ///using CaseConversion;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///#if !CSHARP30
        ///using System.Collections.Concurrent;
        ///#endif
        ///
        ///namespace OrclPower {
        ///#region Classes Supplemental to Hydrator
        ///    /// &lt;summary&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrclPower {
            get {
                return ResourceManager.GetString("OrclPower", resourceCulture);
            }
        }
    }
}
