CREATE USER odpt IDENTIFIED BY odpt;

GRANT CONNECT TO odpt;
GRANT CREATE SESSION TO odpt;
GRANT GRANT ANY PRIVILEGE TO odpt;
GRANT UNLIMITED TABLESPACE TO odpt;
GRANT CREATE SEQUENCE TO odpt;
GRANT CREATE TABLE TO odpt;
GRANT CREATE VIEW TO odpt;
GRANT CREATE PROCEDURE TO odpt;
GRANT CREATE TYPE TO odpt;